# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thisisforthivy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://strapiapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b371e19e1e9b4804bc35e2bba64158af }}
        password: ${{ secrets.AzureAppService_ContainerPassword_46c9747051274ac8a0603c972fb3297a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: strapiapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b371e19e1e9b4804bc35e2bba64158af }}/strapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thisisforthivy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9505932136c84917bf2f1bb76640712e }}
        images: 'strapiapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b371e19e1e9b4804bc35e2bba64158af }}/strapi:${{ github.sha }}'